#!/usr/bin/env bash
set -euo pipefail

input_file="${1:-tool/dart_defines.env}"
output_file="${2:-ios/Flutter/DartDefines.xcconfig}"

if [[ ! -f "$input_file" ]]; then
  echo "Missing $input_file"
  echo "Create it by copying tool/dart_defines.env.example → tool/dart_defines.env"
  exit 1
fi

encoded_defines=()

trim() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "$value"
}

while IFS= read -r raw || [[ -n "$raw" ]]; do
  raw="${raw%$'\r'}"
  local_line="$(trim "$raw")"
  [[ -z "$local_line" ]] && continue
  [[ "$local_line" == \#* ]] && continue

  if [[ "$local_line" != *"="* ]]; then
    echo "Invalid line (expected KEY=VALUE): $raw" >&2
    exit 1
  fi

  key="$(trim "${local_line%%=*}")"
  value="$(trim "${local_line#*=}")"

  [[ -z "$key" ]] && continue
  [[ -z "$value" ]] && continue

  define="${key}=${value}"
  b64="$(printf '%s' "$define" | base64 | tr -d '\n')"
  encoded_defines+=("$b64")
done < "$input_file"

if [[ "${#encoded_defines[@]}" -eq 0 ]]; then
  echo "No non-empty KEY=VALUE pairs found in $input_file" >&2
  exit 1
fi

joined="$(IFS=,; echo "${encoded_defines[*]}")"

cat > "$output_file" <<EOF
// Generated by \`bash tool/gen_dart_defines_xcconfig.sh\`.
// Source: $input_file
//
// This file is gitignored. Do not commit SDK keys.
DART_DEFINES = \$(inherited),$joined
EOF

echo "Wrote $output_file"

